Add check for existence of new function before calling it to fix usage of golden ration in older versions of vim/nvim
roman/golden-ratio pull request #42
Opened 2022-06-22 19:30 UTC by jgcaruso

An early return was added to golden ratio to skip resizing if the window type was a "popup".

The function used is a new nvim feature so it doesn't exist in older versions of nvim or vim (what I happen to be using).

This PR checks for existence of the new function before calling it for users who happen to not be able to update their versions of vim/nvim.

**Testing**
On load of vim/nvim, you should not see any errors emitted in the console.

2022-06-26 18:32 UTC, idbrii requested changes
Thanks for the PR.

Could you also adjust the commit message so the first line isn't so long that it trails off?

Thanks!

2022-06-26 18:32 UTC, idbrii commented on plugin/golden_ratio.vim
> +  if exists('win_gettype') && win_gettype(winnr()) == 'popup'
Must use `*` to check for a function: `exists('*win_gettype')`

2022-06-27 18:43 UTC, jgcaruso commented
I've updated the commit message and re-tested after adding the `*`. Don't usually like force pushing after review started, but I guess it was required in this case 😄

2022-06-28 22:54 UTC, merged

2022-06-28 22:55 UTC, idbrii commented
Even after marking that review comment as resolved, it still thinks there's more to change. I don't understand github's reviews, but the change looks good now.

Thanks!